#define DEBUG true

// CHANGE THIS TO INVALIDATE ALL IDS SAVED ON BOARDS
#define SOFTWARE_VERSION "001"
// MEMORY REGISTER ADDRESS OF BOARD IDENTITY
#define IDENTITY_ADDRESS 0x20
// BYTE LENGTH OF BOARD IDENTITY
#define DEVICE_ID_LEN 1

// VALVE CONTROL PIN
#define VALVE_CONTROL 2
