#define DEBUG true

// CHANGE THIS TO INVALIDATE ALL IDS SAVED ON BOARDS
#define SOFTWARE_VERSION "001"
// MEMORY REGISTER ADDRESS OF BOARD IDENTITY
#define IDENTITY_ADDRESS 0x20
// BYTE LENGTH OF BOARD IDENTITY
#define DEVICE_ID_LEN 1

#define MAX_MSG_LEN 3
#define VALVE_CONTROL 2

// COMMAND CODES
#define SET_ID 0x05
#define OPEN_VALVE 0x06
#define CLOSE_VALVE 0x07
#define IDENTIFY 0x08
#define SYN 0x09
#define ACK 0x10
#define END_OF_CHAIN 0x11

// MESSAGE DESTINATION CODES
#define MASTER 0x01
#define EVERYONE 0x00
#define FIRST_UNIDENTIFIED 0x02
